---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: accounts
spec:
  storageClassName: "ocs-storagecluster-ceph-rbd"
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
