---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: accounts-api
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: accounts-api
    template:
      ref: accounts-api
