---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: accounts-api
spec:
  params:
    - name: git-revision
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: content-type
    - name: pusher-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        labels:
          tekton.dev/pipeline: accounts-api
        name: accounts-api-$(uid)
      spec:
        params:
          - name: APP_NAME
            value: $(tt.params.git-repo-name)
          - name: GIT_REPO
            value: $(tt.params.git-repo-url)
          - name: GIT_REVISION
            value: $(tt.params.git-revision)
        pipelineRef:
          name: accounts-api
        workspaces:
        - name: workspace
          persistentVolumeClaim:
            claimName: accounts-api-pvc
